# Generated by Django 5.0.3 on 2024-03-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameServerModel',
            fields=[
                ('serverId', models.AutoField(primary_key=True, serialize=False)),
                ('firstPlayerId', models.IntegerField(default=-1)),
                ('secondPlayerId', models.IntegerField(default=-1)),
                ('state', models.CharField(default='', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('gameId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField(default=-1)),
                ('userUsername', models.CharField(max_length=50)),
                ('opponentId', models.IntegerField(default=-1)),
                ('opponentUsername', models.CharField(max_length=50)),
                ('userScore', models.IntegerField(default=-1)),
                ('opponentScore', models.IntegerField(default=-1)),
                ('isWin', models.BooleanField(default=False)),
                ('gameDate', models.DateField(default='0000-00-00')),
                ('gameTime', models.TimeField(default='00:00')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingPlayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('language', models.CharField(default='French', max_length=50)),
                ('color', models.CharField(default='white', max_length=50)),
                ('music', models.IntegerField(default=0)),
                ('nbGamePlayed', models.IntegerField(default=0)),
                ('nbGameWin', models.IntegerField(default=0)),
                ('nbGameLose', models.IntegerField(default=0)),
                ('nbTouchedBall', models.IntegerField(default=0)),
                ('nbAce', models.IntegerField(default=0)),
                ('LongestExchange', models.IntegerField(default=0)),
                ('nbPointMarked', models.IntegerField(default=0)),
                ('nbPointLose', models.IntegerField(default=0)),
                ('key1', models.CharField(default='KeyA', max_length=50)),
                ('key2', models.CharField(default='KeyD', max_length=50)),
                ('key3', models.CharField(default='ArrowLeft', max_length=50)),
                ('key4', models.CharField(default='ArrowRight', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
