# Generated by Django 5.0.3 on 2024-03-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameservermodel',
            name='serverAddr',
        ),
        migrations.AlterField(
            model_name='gameservermodel',
            name='firstPlayerAddr',
            field=models.CharField(default=-1, max_length=20),
        ),
        migrations.AlterField(
            model_name='gameservermodel',
            name='secondPlayerAddr',
            field=models.CharField(default=-1, max_length=20),
        ),
    ]
