version: '3.8'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      - main
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      retries: 3
      timeout: 5s

  front:
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    volumes:
      - ./front-end/src:/app/src
    networks:
      - main
    restart: always
    init: true
    ports:
      - "3000:3000"

  django:
    container_name: django
    build:
      context: ./
      dockerfile: ./back-end/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    networks:
      - main
    env_file: .env
    ports:
      - "8080:8000"
networks:
  main:
    name: main
    driver: bridge
